### ISSUE TITLE
Unable to import NPM package in Angular app

### ISSUE THREAD

**Issue by codyuhi** [brigadecore/brigade-sdk-for-js#13]
When trying to import the npm package for @brigadecore/brigade-sdk in app.module.ts in an Angular application, the app does not build properly.
The content of my app.module.ts file is:
```import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import { TopbarComponent } from './topbar/topbar.component';
import { APIClient } from '@brigadecore/brigade-sdk';

@NgModule({
  declarations: [
    AppComponent,
    DashboardComponent,
    SidebarComponent,
    TopbarComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    APIClient
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
And running `ng serve` produces this command line output:

```
Error: node_modules/@brigadecore/brigade-sdk/dist/api_client.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
This likely means that the library (@brigadecore/brigade-sdk) which declares APIClient has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and 
update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
8 export declare class APIClient {
                       ~~~~~~~~~
```

**Comment by radu-matei** [comment]
In the meantime, I am trying to import the library in a new Angular app and getting the following error:

```
Error: ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'http' in '/home/radu/projects/src/github.com/misc/angular10-ivy-test/brigade-ivy/node_modules/eventsource/lib'

Error: ./node_modules/@brigadecore/brigade-sdk/dist/rest_machinery/client.js
Module not found: Error: Can't resolve 'https' in '/home/radu/projects/src/github.com/misc/angular10-ivy-test/brigade-ivy/node_modules/@brigadecore/brigade-sdk/dist/rest_machinery'

Error: ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'https' in '/home/radu/projects/src/github.com/misc/angular10-ivy-test/brigade-ivy/node_modules/eventsource/lib'
```

**Comment by krancour** [comment]
@radu i think you might need a polyfill?

Maybe?

In the non-Angular web demo I created, I used webpack and told it to not both polyfilling `http` and it worked. 🤷 

https://github.com/krancour/brigade-sdk-for-js/blob/master/examples/browser/webpack.config.js#L16

**Comment by radu-matei** [comment]
Yeah, adding that to `package.json` in a top-level `browser` object solves this issue.

**Comment by krancour** [comment]
@radu-matei do you get the same issue as the OP after that?

**Comment by radu-matei** [comment]
I just got a plain Angular 11 using the SDK within a component - https://github.com/radu-matei/angular-brigade-sdk-test

Add your Brigade API server and password, then run `ng serve`, then navigate to `localhost:4200/xyz` - this will request a token using the SDK.

Your issue could come from trying to use the SDK in `app.module.ts` rather than in a component, but this is just a guess at this point.

**Comment by codyuhi** [comment]
Thanks, @radu-matei !  I looked at your code and noticed that you weren't importing brigade-sdk in the app.module.ts file as a module, but were importing it directly onto whatever component as needed.  The code in the component looked like this:
```
import * as brigade from '@brigadecore/brigade-sdk';
@Component({
 . . .
})

export class componentName implements OnInit {
  apiAddress = '<API_ADDRESS>';
  rootPassword = '<ROOT_PASSWORD>';
  . . .
  async getToken() {
    let client = new brigade.APIClient(this.apiAddress, '');
    let token = await client
      .authn()
      .sessions()
      .createRootSession(this.rootPassword)
      .catch((err) => {
        console.error(err);
      });
  }
}
```
That got my original error message to go away.
Then to get rid of the HTTP errors that you mentioned in your comment above, I added this browser definition to package.json:
```
"browser": {
    "http": false,
    "https": false,
    "net": false,
    "path": false,
    "stream": false,
    "tls": false
  }
```
With all that resolved, the Angular app built properly and I was able to use the SDK to interact with Brigade.

**Comment by radu-matei** [comment]
Yeah - that was my initial guess (I actually edited the comment out, because it was just a guess) - I don't think you need the SDK as a top-level import in `AppModule` - so I hope this unblocks you going forward.

I'm also happy to look at issues in Kashti, so once you publish a branch with the work in progress I'm happy to chat about specific things.

**Comment by krancour** [comment]
@radu-matei thanks for the help bringing a swift resolution to this.
